{{- range $name := list "loki" "mimir" "tempo" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  namespace: {{ $.Release.Namespace }}
data:
  config.yaml: |
{{ $.Files.Get (printf "configs/%s.yaml" $name) | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: {{ .Release.Namespace }}
data:
  config.alloy: |
{{ tpl (.Files.Get "configs/alloy.alloy") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Release.Namespace }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Mimir
        uid: mimir
        type: prometheus
        access: proxy
        url: http://mimir:9009/prometheus
        isDefault: true
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki:3100
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
